[package]
name = 'rrustpanic'
version = '0.1.0'
edition = '2018'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
# extendr-api = '*'

# use the local version of extendr-api cargo library
[dependencies.extendr-api]
path = "/Users/shrektan/Documents/RWD/extendr/extendr-api/"
