# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rrustpanic_wrappers", use_symbols = TRUE, package_name = "rrustpanic")

#' @docType package
#' @usage NULL
#' @useDynLib rrustpanic, .registration = TRUE
NULL

#' @export
run <- function(x) .Call(wrap__run, x)

